### ISSUE TITLE
关于插件的咨询

### ISSUE THREAD

**Issue by stonezhu870** [beetlex-io/Bumblebee#87]
bumblebee的版本为1.4.2.3

我自己写一个插件，我可以在插件中修改get或者post来的request中的参数吗？

我在httpRequest中没有找到相关方法？还望作者指导

**Comment by IKende** [comment]
暂只支持header的修改，body那一块不支持，实现实只能自行修改源码。

**Comment by stonezhu870** [comment]
我在插件中，试图使用此方法，直接修改掉请求中的参数，试验了一下，不行。
![image](https://user-images.githubusercontent.com/3832691/98891004-32474700-24d8-11eb-8e94-d1e6acf19264.png)

我的思路是：
如果我要修改，是不是修改BeetleX.FastHttpApi.HttpRequest，从Stream中拿出参数，暴露给外面修改，然后BumbleBee项目中，向下游请求时，从我处理过的参数集合中拿值？
![image](https://user-images.githubusercontent.com/3832691/98891261-cca78a80-24d8-11eb-9a6e-dd0c0575f786.png)

**Comment by IKende** [comment]
可以尝试一下，不能用`Stream.Flush()`改用`Stream.Position=0`.
