### ISSUE TITLE
插件的咨询

### ISSUE THREAD

**Issue by stonezhu870** [beetlex-io/Bumblebee#93]
现有的插件机制，是否支持我拿到接口的响应报文，然后进行加工并返回给调用者。

我看了IRespondingHandler，即便我改了Data，也无法影响给你调用者的返回。

补充一下，我在IRequestingHandler中调试了一下，拿不到客户端Post上来的参数，Get上来的参数是可以拿到的。

![image](https://user-images.githubusercontent.com/3832691/104142776-f0635000-53f7-11eb-9a2c-35e7721d4883.png)

e.Request.Stream.ReadToEnd()
![image](https://user-images.githubusercontent.com/3832691/104142855-4506cb00-53f8-11eb-8f69-01d0f53dbbee.png)

e.Request.Data
![image](https://user-images.githubusercontent.com/3832691/104142865-4fc16000-53f8-11eb-8874-e91668b97639.png)

还请作者解答，谢谢！

**Comment by eddyyuen** [comment]
try this 
e.Request.Stream.ReadString(..)

**Comment by stonezhu870** [comment]
> .

您介绍的方法的确可用，读过post参数后（stream被读过后），即使把stream.position=0置位后，后面正常请求依然会报错。

**Comment by beetlex-io** [comment]
这个IRespondingHandler现阶段只是用于记录响应的流修改，无法修改调整。这些功能只能修改代码来完成。

**Comment by stonezhu870** [comment]
> 这个IRespondingHandler现阶段只是用于记录响应的流修改，无法修改调整。这些功能只能修改代码来完成。

首先感谢解答。
我想实现的是类似于聚合的一个插件，我也看了Bumblebee.Aggregation.dll中的实现，现在例子中的方法只支持get请求。
我想拿到客户端post请求上的参数，在插件中判断，如果包含某个特殊的key, 那么除了完成客户端原来的这次请求外（根据控制台配置的路由），还另外发起一次单独的请求，然后把两次请求的结果聚合一下，返回到客户端。

基于目前插件的机制和开放的api情况，我觉得不修改Bumblebee源码，基本无法实现。

**Comment by beetlex-io** [comment]
Bumblebee.Aggregation的实现其实是基本requesting来做的，拦后自己用httpclient请求响应，并不走网关内部

**Comment by eddyyuen** [comment]
> > 这个IRespondingHandler现阶段只是用于记录响应的流修改，无法修改调整。这些功能只能修改代码来完成。
> 
> 首先感谢解答。
> 我想实现的是类似于聚合的一个插件，我也看了Bumblebee.Aggregation.dll中的实现，现在例子中的方法只支持get请求。
> 我想拿到客户端post请求上的参数，在插件中判断，如果包含某个特殊的key, 那么除了完成客户端原来的这次请求外（根据控制台配置的路由），还另外发起一次单独的请求，然后把两次请求的结果聚合一下，返回到客户端。
> 
> 基于目前插件的机制和开放的api情况，我觉得不修改Bumblebee源码，基本无法实现。

为什么不通过URI / HEADER的参数来判断呢，这样才比较符合实际吧。
另外单独请求，理论上不应该走网关内部，要自己实现。
那么我觉得，插件是可以实现这样的需求的。

**Comment by stonezhu870** [comment]
> > > 这个IRespondingHandler现阶段只是用于记录响应的流修改，无法修改调整。这些功能只能修改代码来完成。
> > 
> > 
> > 首先感谢解答。
> > 我想实现的是类似于聚合的一个插件，我也看了Bumblebee.Aggregation.dll中的实现，现在例子中的方法只支持get请求。
> > 我想拿到客户端post请求上的参数，在插件中判断，如果包含某个特殊的key, 那么除了完成客户端原来的这次请求外（根据控制台配置的路由），还另外发起一次单独的请求，然后把两次请求的结果聚合一下，返回到客户端。
> > 基于目前插件的机制和开放的api情况，我觉得不修改Bumblebee源码，基本无法实现。
> 
> 为什么不通过URI / HEADER的参数来判断呢，这样才比较符合实际吧。
> 另外单独请求，理论上不应该走网关内部，要自己实现。
> 那么我觉得，插件是可以实现这样的需求的。

的确如您所说的，参数是可以放在header中的，现在我的变通方案也是这么做的。
之前放在业务参数中传参，主要是为了VUE中调用起来方便。
聚合的请求如果不走网关内部，那么我在控制台设置的server的权重等设置控制项就要自己实现一次。

**Comment by eddyyuen** [comment]
> > > > 这个IRespondingHandler现阶段只是用于记录响应的流修改，无法修改调整。这些功能只能修改代码来完成。
> > > 
> > > 
> > > 首先感谢解答。
> > > 我想实现的是类似于聚合的一个插件，我也看了Bumblebee.Aggregation.dll中的实现，现在例子中的方法只支持get请求。
> > > 我想拿到客户端post请求上的参数，在插件中判断，如果包含某个特殊的key, 那么除了完成客户端原来的这次请求外（根据控制台配置的路由），还另外发起一次单独的请求，然后把两次请求的结果聚合一下，返回到客户端。
> > > 基于目前插件的机制和开放的api情况，我觉得不修改Bumblebee源码，基本无法实现。
> > 
> > 
> > 为什么不通过URI / HEADER的参数来判断呢，这样才比较符合实际吧。
> > 另外单独请求，理论上不应该走网关内部，要自己实现。
> > 那么我觉得，插件是可以实现这样的需求的。
> 
> 的确如您所说的，参数是可以放在header中的，现在我的变通方案也是这么做的。
> 之前放在业务参数中传参，主要是为了VUE中调用起来方便。
> 聚合的请求如果不走网关内部，那么我在控制台设置的server的权重等设置控制项就要自己实现一次。

并不需要自己实现。
例如本地网关 http://127.0.0.1:9000/，外网 http://10.0.0.1:9000/
客户端请求：http://10.0.0.1:9000/api1
聚合插件用 HttpClient 额外请求网关地址:http://127.0.0.1:9000/api2 .
这样你两次的请求都是走网关的。

至于 e.Request.Stream 可以尝试下 CopyTo 方法复制一个对象。我没试过，就算成功这也不是个好办法。

**Comment by stonezhu870** [comment]
> > > > > 这个IRespondingHandler现阶段只是用于记录响应的流修改，无法修改调整。这些功能只能修改代码来完成。
> > > > 
> > > > 
> > > > 首先感谢解答。
> > > > 我想实现的是类似于聚合的一个插件，我也看了Bumblebee.Aggregation.dll中的实现，现在例子中的方法只支持get请求。
> > > > 我想拿到客户端post请求上的参数，在插件中判断，如果包含某个特殊的key, 那么除了完成客户端原来的这次请求外（根据控制台配置的路由），还另外发起一次单独的请求，然后把两次请求的结果聚合一下，返回到客户端。
> > > > 基于目前插件的机制和开放的api情况，我觉得不修改Bumblebee源码，基本无法实现。
> > > 
> > > 
> > > 为什么不通过URI / HEADER的参数来判断呢，这样才比较符合实际吧。
> > > 另外单独请求，理论上不应该走网关内部，要自己实现。
> > > 那么我觉得，插件是可以实现这样的需求的。
> > 
> > 
> > 的确如您所说的，参数是可以放在header中的，现在我的变通方案也是这么做的。
> > 之前放在业务参数中传参，主要是为了VUE中调用起来方便。
> > 聚合的请求如果不走网关内部，那么我在控制台设置的server的权重等设置控制项就要自己实现一次。
> 
> 并不需要自己实现。
> 例如本地网关 [http://127.0.0.1:9000/，外网](http://127.0.0.1:9000/%EF%BC%8C%E5%A4%96%E7%BD%91) http://10.0.0.1:9000/
> 客户端请求：http://10.0.0.1:9000/api1
> 聚合插件用 HttpClient 额外请求网关地址:http://127.0.0.1:9000/api2 .
> 这样你两次的请求都是走网关的。
> 
> 至于 e.Request.Stream 可以尝试下 CopyTo 方法复制一个对象。我没试过，就算成功这也不是个好办法。

感谢解答。聚合请求中再向网关发起一次请求，的确是一个好方法。再配合通用参数的存法，应该是可以解决我眼下的问题。

单就讨论这个post参数的话题：
e.Request.Stream.CopyTo ，我之前也试过，可以拿到post参数，但是因为Request的流被读取了，也会影响网关执行完插件后续的代码执行。
