### ISSUE TITLE
网关使用插件失效问题

### ISSUE THREAD

**Issue by xueandfeng** [beetlex-io/Bumblebee#94]
使用gateway.Pluginer.SetAgentRequesting("xx");使用代理请求下插件时候无效。
https://github.com/beetlex-io/Bumblebee/blob/master/Bumblebee/Routes/UrlRoute.cs#L34
看这里是进行重新实例化对象。而导致在Gateway.cs网关启用的插件无效

**Comment by beetlex-io** [comment]
gateway.Pluginer和urlRoute.Pluginer是两个独立的插件实像，gateway.Pluginer是针对全局，而urlRoute.Pluginer则针对当前路由。

**Comment by xueandfeng** [comment]
好的。我好像知道了
